spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.1.10

  

#PRODUCT:
#  ribbon:
#    NFLoadBalancerRulerClassName: com.netflix.loadbalancer.RandomRule  #指定负载均衡的方式
env:
  test12

girl: 
  name: yj
  age: 181
